site_name: ECHOYUN
site_url: https://echoyun.xyz/
site_author: Echo Ma
site_description: >-
  This is a personal blog hosted on Github Page. 
  Thanks to Github Page and Mkdocs-material along with the related opensource projects.
  Truely thanks to the authors who work on those projects.

theme:
  name: material
  # custom_dir: overrides
  
  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudecho
    # - icon: fontawesome/solid/rss-square
    #   link: /feed_rss_updated.xml
    #   name: RSS recent updated 
    - icon: fontawesome/solid/rss-square
      link: /feed_rss_created.xml
      name: RSS recent created

markdown_extensions:
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta

plugins:
  - search
  - git-revision-date
  - awesome-pages
  - minify:
      minify_html: true
  - rss:
      categories:
        - categories
        - tags
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M:%S +0800"